### ISSUE TITLE
Remove .vscode folder from repository

### ISSUE THREAD

**Issue by jeremy0x** [Eazyisreal/Portfolio#1]
I noticed that your repository contains a .vscode folder. While this folder may be useful for local development, it can cause conflicts and issues when collaborating with others. Additionally, it can contain sensitive information such as personal settings and preferences.
So it's generally advisable not to add it to your public GitHub repository.

**Comment by Eazyisreal** [comment]
Thanks for the feedbacks. I have made necessary changes. 65e6dcf2e03d0ce57847a0a0e175c58793e49f01

**Comment by jeremy0x** [comment]
Great.
Glad to help!
