### ISSUE TITLE
Adjust page's max-width

### ISSUE THREAD

**Issue by jeremy0x** [Eazyisreal/Portfolio#3]
I would suggest the max-width is increased so it fills most laptop's widths, but you might have to adjust the image when that change is made.

Below is a comparison between an normal size laptop view and a relatively large screen view.

| Laptop          | Large Screen           |
| ----------------- | ----------------- |
| ![laptop](https://user-images.githubusercontent.com/87664239/228977849-76ff1182-1ef5-4391-ab21-a6038b9db4f7.png) | ![large scree ](https://user-images.githubusercontent.com/87664239/228977953-ee814704-bec3-4caf-9fd8-7ef22307f2aa.png) |

**Comment by Eazyisreal** [comment]
Max-width on Laptop adjusted. 442bff4bf67b87d61ae162cdc88d0b2201183599

**Comment by jeremy0x** [comment]
Nice! It definitely looks better now on laptop screens!
