### ISSUE TITLE
Page improvements

### ISSUE THREAD

**Issue by jeremy0x** [Eazyisreal/Portfolio#5]
Changes to make:

- Update page `<title>`
- Add favicon on all pages
- Increase `line-height` on texts on Services page and About Me page
- Add spacing to footer elements on mobile
- Update cursor
- Add padding left and right to **Project 1 image** on mobile on **Project Page**
- Use consistent `font-family` on all pages (esp. Projects)
- Change image on Contact Page

**Comment by Eazyisreal** [comment]
Hi Jeremy. I have fixed all issues. Please let me know if you have any more feedback.
