### ISSUE TITLE
Update repository link

### ISSUE THREAD

**Issue by jeremy0x** [Eazyisreal/Portfolio#6]
Hello Eazy!

Below the repository description where you added the link to the project, what's currently there is <https://www.eazyisreal.netlify.app>, clicking on that shows a Privacy Error as seen in the screenshot below:

![image](https://user-images.githubusercontent.com/87664239/229088710-317497f9-5fe4-45fe-a3f0-b5cdcf017427.png)

To avoid this, the right link to the website would be <https://eazyisreal.netlify.app> instead of <https://www.eazyisreal.netlify.app>.

**Comment by Eazyisreal** [comment]
Oh my bad. Thanks for the feedback.  I have updated it now.
